
import './globals.css';
import './custom.css';
import SessionProviderClientComponent from 'components/SessionProviderClientComponent ';


export const metadata = {
  title: 'Bova ',
  // description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
       <link rel="icon" href="/favicon.svg" />
      </head>
      <body className='clickup-chrome-ext_installe clickup-chrome-ext_installed' >
        <SessionProviderClientComponent>
            {children}
        </SessionProviderClientComponent>
      </body>
    </html>
  );
}
