
import './globals.css';
import './custom.css';
import SessionProviderClientComponent from 'components/SessionProviderClientComponent ';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='clickup-chrome-ext_installe clickup-chrome-ext_installed' >       
        <SessionProviderClientComponent> 
            {children}
        </SessionProviderClientComponent>
      </body>
    </html>
  );
}
